baseurl = "http://OberlinMotionLab.github.io/"
languageCode = "en-us"
title = "Oberlin Motion Lab"
theme= "osprey"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true

[Params]
  author = "Ezra Goss"
  logoBig = "/images/logo.png"
  logoSmall = "/images/Mlogo.png"
  favicon = "/images/not.ico"
  copyright = false

[[menu.main]]
  name = "Projects"
  url = "/#work"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/#blog"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 3
